name = "VLCellularAutomataModelingKit"
uuid = "d7fac052-f096-4e0d-8978-7be4a282ec39"
authors = ["Jeffrey Varner <jdv27@cornell.edu>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
JLD2 = "0.5.10"
